export const Messages = {
    Missing_Fields_Required:'Missing required fields',
    User_Exists:'User already exists',
    Register_Fail:'registration failed',
    Login_Fail:'Invalid credentials',
    Login_Sucess:'Login successful',
    Register_Sucess:'user registered successfully',
    User_Data_Fetched: "User data fetched successfully!",
    User_Updated:"User Updated successfully!",
    User_Deleted: "User Deleted successfully!",
    User_Created: "User Created successfully!",
    User_Not_Available: "User Not Available",
    Unauthorized_User: "Unauthorized",
    Duplicate_Email: "Duplicate Email",
    UserAuthenticated: "User Authenticated successfully!",
    Fetch_Error: "Error fetching users",
    Something_went_Wrong: "Something went wrong!",
    Internal_Server_Error: "Internal Server Error",
    Success: "Success",
    Fail: 'Fail',
    Not_Authorized_No_Token: "Not authorized, no token",
    Invalid_Token: "Invalid token.",
    Token_Expired: "Token expired. Please log in again.",
    Token_Expired_Error: "TokenExpiredError",
    Property_Creation_Failed:'Creating property failed',
    Property_Fetching_Success:'Property fetched successfully',
    Property_Fetching_Fail:'Propery fetching failed',
    Image_Adding:'Image added sucessfully',
    Image_Adding_Failure:'Adding image failed',
    Image_Fetching_Success:'Image fetched successfully',
    Image_Fetching_Fail:'Image fetching failed',
    Favorite_Adding:' Favorite added sucessfully',
    Favorite_Adding_Failure:'Adding  favorite failed',
    Favorite_Fetching_Success:' Favorite fetched sucessfully',
    Favorite_Fetching_Failure:'Fetching  favorite failed',
    Invalid_Images_Format:'invalid image',
    Favorite_Removing_Success:'Favorite removed successfully',
    Favorite_Not_Found:'Favorite not found',
    Favorite_Removing_Failure:'Removing favorite failed'

}